### ISSUE TITLE
BUG: Curve Momentum BOT Fails to complete transaction. Error: call revert exception 

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1266] opened 2024-02-12 22:41 UTC
9373-7a2da6ca7f2c1e03.js:1 e Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="allowance(address,address)", data="0x", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)
    at f.makeError (_app-0d8891ab66d15b5f.js:1:189313)
    at f.throwError (_app-0d8891ab66d15b5f.js:1:189427)
    at v.decodeFunctionResult (_app-0d8891ab66d15b5f.js:1:51475)
    at C.<anonymous> (_app-0d8891ab66d15b5f.js:1:88066)
    at Generator.next (<anonymous>)
    at o (_app-0d8891ab66d15b5f.js:1:83674)

![Image](https://github.com/VolumeFi/paloma/assets/701864/877263a1-68a6-41ec-ae93-8acd0226fd3e)

**Comment by verabehr** [comment] 2024-02-13 16:25
Jamie, Fieldtheory and I couldn't reproduce closing as won't fix

**Closed by verabehr** 2024-02-13 16:25 UTC
Labels: bug, wontfix, curvebot
