### ISSUE TITLE
Upgrade Cosmos-SDK to Version 0.47.0

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#72] opened 2023-03-14 23:19 UTC
# Background

Upgrade Paloma and Pigeon to Cosmos-SDK 0.47.0 in https://github.com/cometbft/cometbft/blob/v0.37.0/CHANGELOG.md

# Done when

- [ ] Upgrade paloma and pigeon types impacted by 0.47.
- [ ] Upgrade complete with tests upgraded
- [ ] Dependency packages also upgraded
- [ ] Prepare semver and release notes

**Comment by verabehr** [comment] 2023-04-03 19:20
duplicate of https://github.com/VolumeFi/paloma/issues/93

**Closed by verabehr** 2023-04-03 19:20 UTC
Labels: enhancement
