### ISSUE TITLE
BUG: 12Hour Returns in the Palomabot tables are all 0s

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#269] opened 2023-05-31 23:36 UTC
The 24-hour column is all zeros

![Image](https://github.com/VolumeFi/paloma/assets/701864/8d58c150-77c0-460e-9d9c-c5af4c8bf677)

**Comment by verabehr** [comment] 2023-06-01 15:16
can no longer reproduce - closing

**Comment by verabehr** [comment] 2023-06-01 15:38
@fieldtheory123 the problem seems to be that there is no 12H value is returned in the API. For example here is the output for Dione


![Image](https://github.com/VolumeFi/paloma/assets/19958639/7e7ac39c-d52f-4fdb-be2e-15697167e907)



`
{"dione":{"id":"dione","symbol":"dione","name":"Dione","platforms":{"ethereum":"0x89b69f2d1adffa9a253d40840b6baa7fc903d697"},"image":{"large":"https://assets.coingecko.com/coins/images/26931/large/dione_200x200.png?1660886063","small":"https://assets.coingecko.com/coins/images/26931/small/dione_200x200.png?1660886063","thumb":"https://assets.coingecko.com/coins/images/26931/thumb/dione_200x200.png?1660886063"},"24H Return":14.878674285693554,"30_day_mean_volume":169181.02837424946,"30_day_mean_marketcap":25936670.38489836,"7D Return":63.62242,"6H Return":9.84,"fully_diluted_valuation":38372332,"best_volume":49026733.506098606,"best_pair":"weth<>dione"},
`

**Closed** 2023-06-06 16:43 UTC
Labels: PalomaBot
