### ISSUE TITLE
BUG: sendToPaloma - EVM tokens are reduced, but Paloma address doesn't receive funds

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#842] opened 2023-10-05 14:10 UTC
I tested send to token to paloma from BNB chain to a validator address (the actual validator paloma address not the cli address)
https://www.notion.so/volumefi/Gravity-Cheat-Sheet-b0fd669082ac4af5b2c4d4b3f1ebe77d?pvs=4#42554424e2c647f7a90105e376f88313

1. Check paloma balance before sending ---> `4,989,999.082221 grain`
2. Check Balance on BNB `90.92839 TESTGRAIN`
3. Approve token amount on BNB `5 Grain`  --> https://bscscan.com/tx/0xe3ba09944de3540e282143b6d1d27a1d96ac87ec2e35348b67107b8c46eac37a
4. sendToPaloma `5 grain` --> https://bscscan.com/tx/0xedbdabffd33f56e550d2d6aa1787913d8810f6ef589696257afa360b278df016
--
5. confirm balance on BNB `85.92839 TESTGRAIN` :white_check_mark: 
6. confirm balance on paloma: `4,989,999.075598GRAIN`actual vs `4,990,004.082221GRAIN` expected --> difference is `5.006623GRAIN` :x: 
7. see error in Paloma logs: :x:  
`Oct 05 02:35:51 m1 palomad[202243]: {"level":"error","module":"server","module":"x/gravity2","cause":"spendable balance  is smaller than 5000000ugrain: insufficient funds","claim type":1,"id":"\u000b\ufffd\u0016_\ufffd\ufffdU\ufffd=\u000bb\ufffdMJF\ufffd\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0006\ufffdԦ\ufffd\ufffd\ufffd\ufffd{}i\ufffd{M\ufffd\ufffd\u001a\ufffd2\ufffdi\ufffdj\u007f>^\ufffd\ufffdn\ufffd\ufffde\ufffd","nonce":"6","time":"2023-10-05T02:35:51Z","message":"Failed deposit"}`

**Comment by taariq** [comment] 2023-12-03 14:57
Moving this to TO-DO until Pigeon Feed is up.

**Comment by byte-bandit** [comment] 2024-03-06 16:55
Looks like there were not enough funds to be allocated back to the address. They should have been there, see: https://github.com/cosmos/cosmos-sdk/blob/main/x/bank/keeper/keeper.go#L281

I will run a fresh test run to see if I can reproduce.

**Comment by byte-bandit** [comment] 2024-03-08 08:56
@taariq I have pivoted to the attestation stuff for now, so no new insights on this yet. I'll come back to it once attestation stuff is done.

**Comment by byte-bandit** [comment] 2024-06-12 08:45
> @byte-bandit is it ready for me to give this another test?

You can test it on a private test net, yes. We need to wait for Paloma `v1.15.0` and Pigeon `v1.12.0` to be rolled out, and Compass `v1.1.0` to be deployed to target chains in order to test this on main or pub test net.

**Comment by verabehr** [comment] 2024-07-15 21:25
- Confirm balance on paloma before send: 188.6933 GRAIN
- balance on Arbitrum 5 GRAIN
- approve send of 4 GRAIN: https://arbiscan.io//tx/0x61d481164ceed374fb320e2ab962df711086b0fecb3339ac2d6007daac9524a0
-

**Comment by taariq** [comment] 2024-07-15 23:12
@verabehr does this mean the transfer worked or that it failed?

**Comment by verabehr** [comment] 2024-07-16 15:09
@taariq it worked

**Closed** 2024-07-16 15:09 UTC
Labels: bug, paloma, Skyway, gas-management, bridge
