### ISSUE TITLE
BUG: Leverage Bot error ContractFunctionExecutionError: Address "[object Object]" is invalid.

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1230] opened 2024-01-28 23:13 UTC
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

error when trying to create leverage bot with ETH collateral. 

Preparing transaction hash...
9373-7a2da6ca7f2c1e03.js:1 e ContractFunctionExecutionError: Address "[object Object]" is invalid.

Raw Call Arguments:
  from:   0x2F1b8e7eC4b927510fCE0a6080B32eac4C833B25
  to:     [object Object]
  value:  0.35 ETH
  data:   0x707c96ae0000000000000000000000000000000000000000000000000000000000000180000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc20000000000000000000000000000000000000000000000f1934d4be9e8d801800000000000000000000000000000000000000000000000000000000000000004000000000000000000000000d3e576b5dcde3580420a5ef78f3639ba9cd1b9670000000000000000000000000000000000000000000000000000000000000700000000000000000000000000000000000000000000000000000000000000037800000000000000000000000000000000000000000000000000000000000001f4000000000000000000000000000000000000000000000000000000000000006400000000000000000000000000000000000000000000000000000007bd67fe210000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000001e0000000000000000000000000000000000000000000000000000000000000001000000000000000000000000eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003782dace9d9000000000000000000000000000000000000000000000000000003782dace9d9000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000001b53016504d1071c
 
Contract Call:
  address:   [object Object] 

function:  create_bot((address[11] route, uint256[5][5] swap_params, uint256 amount, uint256 expected, address[5] pools)[], address collateral, uint256 debt, uint256 N, address callbacker, uint256[] callback_args, uint256 leverage, uint256 deleverage_percentage, uint256 health_threshold, uint256 expire, uint256 number_trades, uint256 interval)
  args:                ([[["0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE","0x0000000000000000000000000000000000000000","0x0000000000000000000000000000000000000000","0x0000000000000000000000000000000000000000","0x0000000000000000000000000000000000000000","0x0000000000000000000000000000000000000000","0x0000000000000000000000000000000000000000","0x0000000000000000000000000000000000000000","0x0000000000000000000000000000000000000000","0x0000000000000000000000000000000000000000","0x0000000000000000000000000000000000000000"],[[0,0,0,0,0],[0,0,0,0,0],[0,0,0,0,0],[0,0,0,0,0],[0,0,0,0,0]],"250000000000000000","250000000000000000",["0x0000000000000000000000000000000000000000","0x0000000000000000000000000000000000000000","0x0000000000000000000000000000000000000000","0x0000000000000000000000000000000000000000","0x0000000000000000000000000000000000000000"]]], 0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2, 4456279545128790000000, 4, 0xd3e576b5dcde3580420a5ef78f3639ba9cd1b967, [1,"1968918995475171100"], 888, 500, 100, 33242480161, 1, 30)
  sender:    0x2F1b8e7eC4b927510fCE0a6080B32eac4C833B25

See picture 
![IMG_20240128_151047_863](https://github.com/VolumeFi/paloma/assets/701864/02bf93cf-1b4e-4274-bda7-8fa37308e5d3)

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

No contract execution errors

**Comment by jamie088** [comment] 2024-01-29 13:18
@taariq Can I get this user info for this tx? like computer system(Max or windows), browser, wallet type, and user area. Because I couldn't reproduce this issue with his wallet. I tried on Google, Firefox (Metamask ), and Frame (Vivaldi)

**Comment by jamie088** [comment] 2024-01-29 13:29
Fixed with https://github.com/VolumeFi/palomabot/pull/347.

**Closed** 2024-01-29 14:50 UTC
Labels: bug, PalomaBot, curvebot
