### ISSUE TITLE
[BUG] Lightnode activation doesn't work

### ISSUE THREAD

**Issue by byte-bandit** [VolumeFi/paloma#2100] opened 2024-09-02 14:39 UTC
```
❯ sh $HOME/Downloads/setup.sh activate
v1: Pulling from palomachain/lightnode-client
Digest: sha256:418957d731a6b98460d2876fdd1d82e05762e864291af2ab261d1d6979c64bac
Status: Image is up to date for palomachain/lightnode-client:v1
Activating node CL_LNS_1
Error: rpc error: code = NotFound desc = rpc error: code = NotFound desc = account paloma1sdffvvaaz0l7ux3trnd4rnf6ssz7uqfv29nze3 not found: key not found
```

https://etherscan.io/tx/0xe55e28bd495cbd1f1366190ceff5bf26a358a12a095af30d385bbfc0d318eb82

**Comment by maharifu** [comment] 2024-09-04 08:03
This was caused by the sale frontend calling the wrong contract address for some of the chains. It should be fixed already.

**Closed by maharifu** 2024-09-04 08:03 UTC
Labels: paloma, light-node-sale
