### ISSUE TITLE
bug: Repay does not work for Curve Healthy Juice bot.

### ISSUE THREAD

**Issue by wc117** [VolumeFi/paloma#1568] opened 2024-05-15 14:18 UTC
# What is happening?

I created Curve Juice Leverage Bot when the BTC price was 61.6K with 1% profit taking yesterday. And it is 64.2K now so I think they should be repayed by the backend script but it didn't work yet. Please check the backend script and make the repay works.

I am attaching the create bot transaction hashes.

https://etherscan.io/tx/0x694ef89a123a11b3ccf882a05184c177116676ca933f9a14095411dc3cb1ae8a
https://etherscan.io/tx/0xec5b9ecd84fb8e4ec69c4e805f3f32ef8562b92d03fc415df3a0cc7042a023da

**Comment by verabehr** [comment] 2024-05-15 16:09
https://github.com/VolumeFi/curve-healthy-bot/blob/main/curve-leverage.js#L586

**Comment by rootedbox** [comment] 2024-05-15 21:42
I think the issue is that profit_taking wasn't set in the db.. I'm trying to figure out why it didn't get set

**Comment by rootedbox** [comment] 2024-05-16 02:18
For now all I could do was manually put in the profit_taking and add logging to the robot to see what is actually coming in via the contract. 

![Image](https://github.com/VolumeFi/paloma/assets/3997890/a78984bb-0714-4e5d-b446-75de2ec2903b)

one weird thing is that normally where it says topic would be the name of the event.. but in this case it's not there.

we might need to test this by creating a bot now that we have logging

**Comment by rootedbox** [comment] 2024-05-20 23:12
@wc117 the event is missing profit taking.. so this will never complete. needs to be fixed in contract cc: @verabehr 
 {"0":"2","1":"0x4d2347F9671BeaE14c6dF46EdE2a488556DF258F","2":"0xed37883E8a5F3EaE2dAE18Da78f3C9cF11eEeAE6","3":"0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2","4":"100000000000000","5":"0xf939E0A03FB07F59A73314E73794Be0E57ac1b4E","6":"1000000000000000000","7":"10","8":"439","9":"5000","10":"1191","11":"100","12":"33251907869","13":"0xd3e576B5DcDe3580420A5Ef78F3639BA9cd1B967","14":["1","338318072587083"],"15":"1","16":"30","deposit_id":"2","owner":"0x4d2347F9671BeaE14c6dF46EdE2a488556DF258F","bot":"0xed37883E8a5F3EaE2dAE18Da78f3C9cF11eEeAE6","collateral":"0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2","collateral_amount":"100000000000000","settlement":"0xf939E0A03FB07F59A73314E73794Be0E57ac1b4E","debt":"1000000000000000000","N":"10","leverage":"439","deleverage_percentage":"5000","health_threshold":"1191","health_threshold_upper":"100","expire":"33251907869","callbacker":"0xd3e576B5DcDe3580420A5Ef78F3639BA9cd1B967","callback_args":["1","338318072587083"],"remaining_count":"1","interval":"30"}

**Comment by wc117** [comment] 2024-05-23 13:51
Curve Healthy Juice bot doesn't have the profit taking field. @verabehr @rootedbox

**Comment by verabehr** [comment] 2024-05-23 14:54
@wc117 I see it in line 73 here though https://etherscan.io/address/0x82E2c99AD31e6119D874B08fbd2C3f9F9fbD1aD8#code 

and also here https://github.com/VolumeFi/Curve-healthy-juice-degen-vyper/blob/master/contracts/factory.vy#L73

**Comment by verabehr** [comment] 2024-05-23 16:32
@wc117 here is where we changed from `health_threshold_upper` to `profit_taking` https://github.com/VolumeFi/Curve-healthy-juice-degen-vyper/commit/5dc7b2ea1140b14358dffc45fd2ca7e0fac0ca27. But we're seeing the event come in with `health_threshold_upper`

**Comment by taariq** [comment] 2024-05-23 21:53
from @rootedbox: I shouldn't have to do anything.. as my code already has profit_taking.. and when i manually set it everything worked.. so we should be good now for new transactions

**Closed by taariq** 2024-05-23 21:53 UTC
Labels: bug

**Comment by verabehr** [comment] 2024-05-23 21:58
The issue was an outdated ABI on the server. This was updated
