### ISSUE TITLE
BUG: Volume Blog Read More links return 404

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#205] opened 2023-05-17 20:02 UTC
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

BUG: Volume Blog Read More links return 404
https://volume.finance/blog/recurring-strategies-with-carbon-the-bancor-team/?

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

Read More Blog links retrieve content.

**Comment by verabehr** [comment] 2023-05-17 20:05
Duplicate of https://github.com/VolumeFi/paloma/issues/206

**Closed by verabehr** 2023-05-17 20:05 UTC
Labels: bug, Volume
