### ISSUE TITLE
BUG: momentum bot search key error in find_best_reserve

### ISSUE THREAD

**Issue by verabehr** [VolumeFi/paloma#386] opened 2023-06-28 16:25 UTC
This code https://github.com/VolumeFi/trading-bots/commit/d4e7856d811b7d643976a39cd6bd9786e64a147a#diff-95448b43e932c7d0d5939589829546d9fe24472037054078bf1cf6b9021ef9b1R72-R79 
seems to cause this `KeyError: 'data'` error

```
Jun 28 15:56:02 lorentz poetry[3484479]: Traceback (most recent call last):
Jun 28 15:56:02 lorentz poetry[3484479]:   File "/root/app/momentum_cache_refresh/cache_db.py", line 160, in warm_cache_loop
Jun 28 15:56:02 lorentz poetry[3484479]:     momentum_scanner_intraday.get_high_returns(**kwargs)
Jun 28 15:56:02 lorentz poetry[3484479]:   File "/root/app/momentum_cache_refresh/momentum_scanner_intraday.py", line 144, in get_high_returns
Jun 28 15:56:02 lorentz poetry[3484479]:     add_best_liquidity(df, dex)
Jun 28 15:56:02 lorentz poetry[3484479]:   File "/root/app/momentum_cache_refresh/momentum_scanner_intraday.py", line 121, in add_best_liquidity
Jun 28 15:56:02 lorentz poetry[3484479]:     best_volume, best_pair, best_reserve = find_best_liquidity(token, dex)
Jun 28 15:56:02 lorentz poetry[3484479]:   File "/root/app/momentum_cache_refresh/momentum_scanner_intraday.py", line 114, in find_best_liquidity
Jun 28 15:56:02 lorentz poetry[3484479]:     best_reserve = find_best_reserve(chain_cgterminal, contract_addr)
Jun 28 15:56:02 lorentz poetry[3484479]:   File "/root/app/momentum_cache_refresh/momentum_scanner_intraday.py", line 79, in find_best_reserve
Jun 28 15:56:02 lorentz poetry[3484479]:     for data in gecko.networks_tokens_pools(chain, contract_addr)["data"]
Jun 28 15:56:02 lorentz poetry[3484479]: KeyError: 'data'
```

The code on the server only had code from Jun 6, all later changes had not been deployed until today. I rolled back the code to the Jun 6 commit for now

**Comment by verabehr** [comment] 2023-06-28 17:36
here is also the sentry link for this error: https://volume-x3.sentry.io/issues/4280896040/?alert_rule_id=14209893&alert_timestamp=1687967248942&alert_type=email&environment=production&project=4505082653573120&referrer=alert_email

**Comment by fieldtheory123** [comment] 2023-06-29 12:55
This turns out to be caused by the endpoint's timeout error (see log below). We are waiting for 10 seconds and it often takes longer and time out. 

Currently communicating with external term to confirm how to solve the time out issue.

`Traceback (most recent call last):
  File "/root/temp/test.py", line 9, in <module>
    df = msi.get_high_returns(dex,lag_return,daily_volume,vol_30,market_cap)
  File "/root/temp/momentum_scanner_intraday.py", line 148, in get_high_returns
    add_best_liquidity(df, dex)
  File "/root/temp/momentum_scanner_intraday.py", line 125, in add_best_liquidity
    best_volume, best_pair, best_reserve = find_best_liquidity(token, dex)
  File "/root/temp/momentum_scanner_intraday.py", line 118, in find_best_liquidity
    best_reserve = find_best_reserve(chain_cgterminal, contract_addr)
  File "/root/temp/momentum_scanner_intraday.py", line 82, in find_best_reserve
    re = gecko.networks_tokens_pools(chain, contract_addr)
  File "/root/temp/gecko.py", line 179, in networks_tokens_pools
    return get_gt("networks", chain, "tokens", contract_addr, "pools")
  File "/root/temp/gecko.py", line 75, in get_gt
    return fetch() #cache_db.try_cache(path, params, fetch)
  File "/root/temp/gecko.py", line 69, in fetch
    return requests.get(
  File "/usr/lib/python3/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 531, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 647, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 532, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.geckoterminal.com', port=443): Read timed out. (read timeout=10)`

**Comment by taariq** [comment] 2023-07-06 13:22
Closing as complete.

**Closed by taariq** 2023-07-06 13:22 UTC
Labels: bug, PalomaBot
