### ISSUE TITLE
Update slippage, repay & create next bot for llamalend bot backend script

### ISSUE THREAD

**Issue by webelf101** [VolumeFi/paloma#1622] opened 2024-05-28 14:06 UTC
- [x] **Repay**
repay args: https://github.com/VolumeFi/llamalend-leverage-lending-bot-/blob/main/llama-leverage.js#L810

- [x] **Create next bot**
callbacker: connection.zap,
callback_args: [0, ControllerID[item.coin_info0.symbol.toUpperCase()][connection.networkName], 0],
swapBytecode:
```
const swapByteCode = await getSwapByteCode(
      connection.crvusdAddress,
      item.token0,
      outputamount / twap counts,
      connection.zap,
      connection.networkName
    );
```

- [x] **Slippage**
please update slippage percentage  to prevent transaction revert for llamalend bot like this:

- token amount is between $0 ~ $10000 --> 1%
- $10000 ~ $100000 --> 0.5%
- $ > 100000 < -> 0.1%

**Comment by verabehr** [comment] 2024-05-29 13:47
@webelf101 I think this is now a duplicate of https://github.com/VolumeFi/paloma/issues/1597?

**Closed** 2024-05-29 18:23 UTC
Labels: enhancement, PalomaBot, curvebot
