### ISSUE TITLE
BUG: DCA BOT API missing values?

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#488] opened 2023-07-19 06:51 UTC
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

DCA bot have a deposit_price and tracking_price values?

@jamie088  checked BE api and these values were missing in API but I am not sure this is correct or not.

Please verify that BE API for DCA bot is working @rootedbox

**Comment by verabehr** [comment] 2023-07-20 13:44
this is a dupe of https://github.com/VolumeFi/paloma/issues/489

**Closed by verabehr** 2023-07-20 13:44 UTC
Labels: bug, PalomaBot
