### ISSUE TITLE
[DEVOPS] We stopped getting alerts when mainnet validator is jailed

### ISSUE THREAD

**Issue by maharifu** [VolumeFi/paloma#1927] opened 2024-07-30 09:09 UTC
Our mainnet validator was jailed today, but we didn't get an alert on discord.

**Comment by verabehr** [comment] 2024-07-31 14:04
this is a duplicate of this https://github.com/VolumeFi/paloma/issues/1884

**Closed by verabehr** 2024-07-31 14:04 UTC
Labels: devops
