### ISSUE TITLE
BUG: Curve TWAP Bot gives Insufficient Amount when TWAP from USDC to ETH 1 trade

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1269] opened 2024-02-12 23:54 UTC
BUG: Curve TWAP Bot gives Insufficient Amount when TWAP from USDC to ETH 1 trade. See picture

![Image](https://github.com/VolumeFi/paloma/assets/701864/3f1ae602-1044-41a1-8411-361228665b43)

**Comment by verabehr** [comment] 2024-02-13 16:26
Jamie, Fieldtheory and I couldn't reproduce closing as won't fix

**Closed by verabehr** 2024-02-13 16:26 UTC
Labels: bug, curvebot
