### ISSUE TITLE
BUG: EuroE Twap Bot Message Fails to relay

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1417] opened 2024-03-24 04:58 UTC
EurE Bot Fails TWAP on Gnosis side after 30 minutes

1. Original Tx: https://etherscan.io/tx/0x996e3a9a1ce6a8bd3203140479e5c8a846f777e42810cf49318b102b435522ff
  * Time: 9:26PM PT
3. Compass-EVM: https://gnosisscan.io/address/0x8ab57eb10950564b9b24fdf5a7abd866fb2f64ce  * No Valset update
  * No SLC
  * No Sentry errors showing bot service failure
4. Balance is on Gnosis: https://gnosisscan.io/address/0x48afa99cd4166d89718cba46db7e1eeb99535b46#internaltx

**Comment by verabehr** [comment] 2024-03-24 10:14
LCD was again stuck, we have a ticket to get an alert but that wasn't done yet, this should be top priority for @rootedbox on Monday https://github.com/VolumeFi/paloma/issues/1395

I restarted lcd and failed over to lcd2 for the following bots

- gnosis offramp
- curve twap
- curve degen leverage
- curve noob leverage
- curve healthy juice

The `remaining counts are going down` as expected, but I dont' see any corresponding messages in the queue or SLCs on gnosis scan so I think something else might be going on


```
{"deposit_id":"35","token0":"0x6c3F90f043a72FA612cbac8115EE7e52BDe6E490","token1":"0x6B175474E89094C44Da98b954EedeAC495271d0F","amount0":"10000000000000000000000","amount1":"10309068729454886950230","depositor":"0x7a16fF8270133F063aAb6C9977183D9e72835428","deposit_price":"1","network_name":"eth","dex_name":"curve","bot":"eure_curve","number_trades":"3","remaining_counts":"1","interval":"180","starting_time":"1711274585","contract":"0xC1880758D240a95a806FF4F61c912e86670ac357","sent_to_mixpanel":"0","create_to_mixpanel":"0","created_at":"2024-03-24 04:26:13","gas_mixpanel":"0","deleverage_percentage":"100","coin_info":{"id":"dai","symbol":"dai","name":"Dai","platforms":
```
This was a few minutes of this posting ☝️ 


Now the bot is no longer in the API at all @rootedbox @webelf101

**Comment by taariq** [comment] 2024-03-24 15:05
@rootedbox @webelf101 I no longer see the balance on Gnosis nor a Gnosis transaction. 

What happened?
https://gnosisscan.io/address/0x48afa99cd4166d89718cba46db7e1eeb99535b46#internaltx

**Comment by taariq** [comment] 2024-03-24 16:07
Okay. @rootedbox @webelf101 I see that the tx processed 6 hours ago: https://gnosis.blockscout.com/address/0x48afa99CD4166D89718cbA46DB7e1eEb99535b46?tab=token_transfers

It appears Gnosis scan is not current.

**Comment by rootedbox** [comment] 2024-03-24 19:13
```
Mar 24 19:03:19 bots-server npm[3718256]: stderr: Traceback (most recent call last):
Mar 24 19:03:19 bots-server npm[3718256]:   File "/home/rootedbox/app/offramp-eure-bot-script/./bot-execute.py", line 258, in <module>
Mar 24 19:03:19 bots-server npm[3718256]: stderr:     asyncio.run(main())
Mar 24 19:03:19 bots-server npm[3718256]:   File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
Mar 24 19:03:19 bots-server npm[3718256]:     return loop.run_until_complete(main)
Mar 24 19:03:19 bots-server npm[3718256]:   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
Mar 24 19:03:19 bots-server npm[3718256]:   File "/home/rootedbox/app/offramp-eure-bot-script/./bot-execute.py", line 253, in main
Mar 24 19:03:19 bots-server npm[3718256]:     await eure_bot(network)
Mar 24 19:03:19 bots-server npm[3718256]:   File "/home/rootedbox/app/offramp-eure-bot-script/./bot-execute.py", line 103, in eure_bot
Mar 24 19:03:19 bots-server npm[3718256]:     deposit_logs = bot_sc_send.events.Deposited.getLogs(fromBlock=i, toBlock=to_block)
Mar 24 19:03:19 bots-server npm[3718256]:   File "/home/rootedbox/.local/lib/python3.10/site-packages/eth_utils/decorators.py", line 20, in _wrapper
Mar 24 19:03:19 bots-server npm[3718256]:     return self.method(objtype, *args, **kwargs)
Mar 24 19:03:19 bots-server npm[3718256]:   File "/home/rootedbox/.local/lib/python3.10/site-packages/web3/contract.py", line 1365, in getLogs
Mar 24 19:03:19 bots-server npm[3718256]: stderr:     logs = self.web3.eth.get_logs(event_filter_params)
Mar 24 19:03:19 bots-server npm[3718256]:   File "/home/rootedbox/.local/lib/python3.10/site-packages/web3/module.py", line 57, in caller
Mar 24 19:03:19 bots-server npm[3718256]:     result = w3.manager.request_blocking(method_str,
Mar 24 19:03:19 bots-server npm[3718256]:   File "/home/rootedbox/.local/lib/python3.10/site-packages/web3/manager.py", line 198, in request_blocking
Mar 24 19:03:19 bots-server npm[3718256]: stderr:     return self.formatted_response(response,
Mar 24 19:03:19 bots-server npm[3718256]:   File "/home/rootedbox/.local/lib/python3.10/site-packages/web3/manager.py", line 171, in formatted_response
Mar 24 19:03:19 bots-server npm[3718256]:     raise ValueError(response["error"])
Mar 24 19:03:19 bots-server npm[3718256]: ValueError: {'code': -32001, 'message': 'Receipt not available for To block 19506347.'}
Mar 24 19:03:19 bots-server npm[3718256]: stderr: Unclosed client session
Mar 24 19:03:19 bots-server npm[3718256]: client_session: <aiohttp.client.ClientSession object at 0x7f981e99fc40>
```

logs from the server.. @webelf101

**Comment by taariq** [comment] 2024-03-24 21:22
@webelf101 is this a Gnosis RPC problem? We were not ble to get the block from Gnosis?

**Comment by verabehr** [comment] 2024-03-25 15:17
@webelf @taariq @rootedbox, so we can close this ticket then?

**Comment by taariq** [comment] 2024-03-25 16:08
@verabehr No.

This ticket needs @webelf101 to confirm what caused the failure on the script so we can rectify it.

**Comment by verabehr** [comment] 2024-03-25 20:52
from @webelf101 

1. All trade were completed 8 hours ago.
2. The service has returned same error.
3. I couldn't add more endpoint to Quicknode because we reached limit.
4. I tried to set free endpoint and it doesn't return error.
5. That means liquify endpoint doesn't work right now but our script can work 

--> upgraded from liquify to quicknode

**Closed by verabehr** 2024-03-25 20:52 UTC
Labels: PalomaBot, curvebot

**Comment by webelf101** [comment] 2024-03-26 12:57
This is RPC endpoint error and I confirmed. We can close this. @verabehr
