### ISSUE TITLE
BUG: All Bots Disappeared around 5:25PM PT.

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1296] opened 2024-02-20 02:29 UTC
starting at https://discord.com/channels/987730379182051408/1014209110637547610/1209313229352730664.

1. No bots available 
2. @rootedbox: _i reverted to an old version but seems to be doing the same thing_
3. Bots started showing up again. Why did this happen and how do we avoid recurrence?

![Image](https://github.com/VolumeFi/paloma/assets/701864/d2d9b87e-c729-4503-926a-13de4e9f1eea)

**Comment by verabehr** [comment] 2024-02-22 14:54
The available logs were not helpful to figure out what happened, potentially it was caused by the site slowdown which was fixed with this https://github.com/VolumeFi/paloma/issues/1295

**Closed by verabehr** 2024-02-22 14:54 UTC
Labels: bug, PalomaBot, curvebot
