### ISSUE TITLE
GNOSIS: Second Failure on Gnosis chain blocking $20K tx.

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#1346] opened 2024-03-06 06:08 UTC
Gnosis chain failing to relay again. Attempts to activate valset failed after stopping and starting Volume validator.

Gnosis contract: https://gnosisscan.io/address/0x0ae9947ee84763e91eb65eae8bf9c961ee92de54

Question: 
1. Does volume not have enough stake to force valset?
2. Will we add logging to Paloma so that we can get awareness of this issue faulty validators?

**Comment by byte-bandit** [comment] 2024-03-06 07:57
@taariq This is the same behaviour we ran into last week, same reason as well. At the moment, I can play fire watch and force valset updates in order to hopefully resolve the situation.

But once we have PF in place, I think we should increase the time we wait before reassigning a message. Some relays will simply naturally take a lot of time due to target chain state, and we should wait before we reattempt and run into this problem. PF will tend to select the highest performing Pigeons, so we can assume that the relayer is stable and the delay is caused by i.e. payload size, target chain activity, etc...

**Comment by byte-bandit** [comment] 2024-03-06 14:16
Another thing we're lacking, there is 0 observability into this at the moment. We know who signed a transaction going out, but we cannot see how attested the result, or what level of consensus we do reach. We should increase our logging on that level to see what's really going on here, and reach out to the validators that are not attesting to find out why.

**Comment by taariq** [comment] 2024-03-06 14:25
@byte-bandit this was something we discussed prior. Will you create a logging release with a forced upgrade so that we will have all pigeons upgrade.

**Closed** 2024-03-07 14:44 UTC
Labels: bug, curvebot
