### ISSUE TITLE
[LIGHTNODE] As a user I want the LightNode to  add  the key to the index and then to the keyring either both happen or none, so we avoid issues

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#2283] opened 2024-10-14 20:31 UTC
As a user I want the LightNode to add the key to the index and then to the keyring either both happen or none, so we avoid issues like we had when user added the key, but not the keyring.

**Acceptance Criteria**
1. Add to Key Index + Add to Keyring: Make sure either both or none happen.

**Comment by maharifu** [comment] 2024-10-15 08:21
This is a duplicate of https://github.com/VolumeFi/paloma/issues/2280

**Closed by maharifu** 2024-10-15 08:21 UTC
Labels: light-node-sale
