### ISSUE TITLE
BUG: Palomabot Pancakeswap bot does not execute deposit. 

### ISSUE THREAD

**Issue by taariq** [VolumeFi/paloma#912] opened 2023-10-26 04:43 UTC
# What is happening?
<details>
  <summary>Section description</summary>
<i>Provide as much context as you can. Give as much context as you can to make it easier for the developers to figure what is happening.</i>
</details>

Palomabot Pancakeswap Momentum bot does not execute deposit. https://www.palomabot.ai/momentum/bot/?dex=pancakeswap_new&lag_return=6&daily_volume=0&vol_30=100000&market_cap=1000000&token=chromaway just approves change of the endpoints and then goes back to the page.

# What is the expected behaviour?
<details>
  <summary>Section description</summary>
<i>If you know, please write down what is the expected behaviour. If you don't know, that's ok. We can have a discussion in comments.</i>
</details>

The Pancakeswap Momentum Bot starts and deposits a transaction.

**Comment by verabehr** [comment] 2023-10-26 13:54
duplicate of https://github.com/VolumeFi/paloma/issues/914

**Closed by verabehr** 2023-10-26 13:54 UTC
Labels: bug
