### ISSUE TITLE
BUG: DCA bot was not running at the expected trading time

### ISSUE THREAD

**Issue by jamie088** [VolumeFi/paloma#416] opened 2023-07-05 14:49 UTC
Checked DCA bot and DCA bot was not running at the expected trading time.
![image](https://github.com/VolumeFi/paloma/assets/83244763/5dec6584-cae4-4d0e-8f76-ea2b25cb4f8e)
It is HK time and a selected bot should have run 10:10pm HK time. but not running.

**Comment by taariq** [comment] 2023-07-05 16:14
Closing. This is as designed as we are using UTC time. Please use the front-end to offset to the user time, based on UTC.

**Comment by jamie088** [comment] 2023-07-05 16:16
I got it.

**Comment by jamie088** [comment] 2023-07-05 16:22
I currently used user local time in the DCA bot so users can set the time with their time zone. If then convert to UTC time always? @taariq

**Comment by taariq** [comment] 2023-07-05 17:44
> I currently used user local time in the DCA bot so users can set and see the time with their time zone. If then convert to UTC time always? @taariq

Yes. Since @rootedbox is inserting all orders with UTC time stamps, we will be UTC time as standard for all orders.

**Comment by jamie088** [comment] 2023-07-06 15:03
The expected trade time has passed, but bot still does not run.

**Comment by rootedbox** [comment] 2023-07-06 16:10
@jamie088 is its running at all?

**Comment by taariq** [comment] 2023-07-07 14:43
@rootedbox the deposit works, but the bot never runs at all. My tx for deposit was complete here: https://etherscan.io/address/0xaa79ed113b5f14565fb5a200cfa28e1fbdb94ef5

however, no tokens were purchased at all.

**Comment by taariq** [comment] 2023-07-11 21:23
Fixed.

**Closed by taariq** 2023-07-11 21:23 UTC
Labels: bug, PalomaBot
